module.exports = {
  id: '1467889',
  displayName: 'Joseph Morse',
  username: 'jnmorse',
  profileUrl: 'https://github.com/jnmorse',
  emails: [{ value: 'tamed.lionheart@gmail.com' }],
  photos: [{ value: 'https://avatars1.githubusercontent.com/u/1467889?v=4' }],
  provider: 'github',
  _raw:
    '{"login":"jnmorse","id":1467889,"node_id":"MDQ6VXNlcjE0Njc4ODk=","avatar_url":"https://avatars1.githubusercontent.com/u/1467889?v=4","gravatar_id":"","url":"https://api.github.com/users/jnmorse","html_url":"https://github.com/jnmorse","followers_url":"https://api.github.com/users/jnmorse/followers","following_url":"https://api.github.com/users/jnmorse/following{/other_user}","gists_url":"https://api.github.com/users/jnmorse/gists{/gist_id}","starred_url":"https://api.github.com/users/jnmorse/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jnmorse/subscriptions","organizations_url":"https://api.github.com/users/jnmorse/orgs","repos_url":"https://api.github.com/users/jnmorse/repos","events_url":"https://api.github.com/users/jnmorse/events{/privacy}","received_events_url":"https://api.github.com/users/jnmorse/received_events","type":"User","site_admin":false,"name":"Joseph Morse","company":null,"blog":"https://josephmorse.me/","location":"NH, USA","email":"tamed.lionheart@gmail.com","hireable":true,"bio":"JavaScript Web developer, Specializing in React.","public_repos":57,"public_gists":5,"followers":28,"following":59,"created_at":"2012-02-24T02:11:08Z","updated_at":"2019-10-02T00:11:44Z"}',
  _json: {
    login: 'jnmorse',
    id: 1467889,
    node_id: 'MDQ6VXNlcjE0Njc4ODk=',
    avatar_url: 'https://avatars1.githubusercontent.com/u/1467889?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jnmorse',
    html_url: 'https://github.com/jnmorse',
    followers_url: 'https://api.github.com/users/jnmorse/followers',
    following_url:
      'https://api.github.com/users/jnmorse/following{/other_user}',
    gists_url: 'https://api.github.com/users/jnmorse/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jnmorse/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jnmorse/subscriptions',
    organizations_url: 'https://api.github.com/users/jnmorse/orgs',
    repos_url: 'https://api.github.com/users/jnmorse/repos',
    events_url: 'https://api.github.com/users/jnmorse/events{/privacy}',
    received_events_url: 'https://api.github.com/users/jnmorse/received_events',
    type: 'User',
    site_admin: false,
    name: 'Joseph Morse',
    company: null,
    blog: 'https://josephmorse.me/',
    location: 'NH, USA',
    email: 'tamed.lionheart@gmail.com',
    hireable: true,
    bio: 'JavaScript Web developer, Specializing in React.',
    public_repos: 57,
    public_gists: 5,
    followers: 28,
    following: 59,
    created_at: '2012-02-24T02:11:08Z',
    updated_at: '2019-10-02T00:11:44Z'
  }
};
